In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("/content/car_fuel_efficiency_2026.csv")

In [ ]:
pd.__version__

'2.2.3'

In [ ]:
df.shape

(10000, 11)

In [ ]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [ ]:
#finding all the unique values in the column
df['fuel_type'].nunique()

3

In [ ]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [ ]:
max_fuel_efficiency_asia = df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()
print(f"Maximum fuel efficiency for cars from Asia: {max_fuel_efficiency_asia} MPG")

Maximum fuel efficiency for cars from Asia: 41.2 MPG

In [ ]:
df['horsepower'].median()

254.0

In [ ]:
df['horsepower'].mode()[0]

np.float64(252.0)

In [ ]:
#finding the value count of all the values in horsepower column
df['horsepower'].value_counts()

horsepower
252.0    174
256.0    168
246.0    168
259.0    165
253.0    165
        ...
322.0      1
330.0      1
175.0      1
178.0      1
320.0      1
Name: count, Length: 153, dtype: int64

In [ ]:
df['horsepower']=df['horsepower'].fillna(252.0)

In [ ]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower               0
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [ ]:
df['horsepower'].median()

252.0

In [ ]:
#Selecting all cars from Asia
df_asia=df[df['origin']=='Asia']

In [ ]:
df_asia

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
...,...,...,...,...,...,...,...,...,...,...,...
9984,2011,Asia,Gasoline,Front-wheel drive,3,2410,6,256.0,4610,20.2,32.4
9987,2004,Asia,Diesel,All-wheel drive,3,2180,6,266.0,4530,18.6,29.0
9990,1975,Asia,Diesel,Front-wheel drive,4,1940,6,236.0,3630,19.7,32.4
9994,1993,Asia,Gasoline,Rear-wheel drive,2,2360,6,257.0,4610,22.2,30.1
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0

In [ ]:
df_asia=df_asia[['vehicle_weight','model_year']]
df_asia

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]

In [ ]:
df_asia.head(7)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [ ]:
df_asia=df_asia[:7]

In [ ]:
X=df_asia.to_numpy()

In [ ]:

# Calculate the transpose of X and XTX
XT = X.T
XTX = np.dot(XT, X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [ ]:
# Invert XTX
XTX_inverse = np.linalg.inv(XTX)
XTX_inverse

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [ ]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [ ]:
w = np.dot(np.dot(XTX_inverse, XT), y)
w

array([0.13644777, 0.2327492 ])

In [ ]:
sum_w = np.sum(w)
sum_w

np.float64(0.36919696904925486)